imports:
    finn-examples: t/data/

git module finn-examples:
    url: git://github.com/atweiden/finn-examples.git
    rev: 32a124e370d851c4fe93e16deb6fd24d171088c3
    drop:
        - README.md
        - UNLICENSE
        - .gitignore
        - .hgignore
