imports:
    finn-examples: t/data/

git module finn-examples:
    url: git://github.com/atweiden/finn-examples.git
    rev: 316bcb7dac9f9e3ed702eb2ec8432e5e1774a1d0
    drop:
        - README.md
        - UNLICENSE
