branches:
    only:
        - master

language: perl6

perl6:
    - latest

sudo: true

env:
    - PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-nom/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/panda/bin:$PATH

before_install:
    # install https://github.com/buildinspace/peru
    - sudo add-apt-repository --yes ppa:buildinspace/peru
    - sudo apt-get --yes update
    - sudo apt-get --yes install peru
    # get finn-examples
    - cd $TRAVIS_BUILD_DIR
    - peru --file=.peru.yml --sync-dir="$PWD" sync

install:
    - rakudobrew build panda
    - panda --notests installdeps .
