branches:
    only:
        - master

language: perl6

perl6:
    - latest

sudo: false

env:
    - PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-nom/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/panda/bin:$PATH

before_install:
    - cd $TRAVIS_BUILD_DIR
    # get t/data
    - git clone https://github.com/atweiden/finn-examples t/data
    - cd t/data
    - git checkout 70d39d18a694c17657f8a9923a84d68d50e45df1

install:
    - cd $TRAVIS_BUILD_DIR
    - rakudobrew build zef
    - zef --deps-only --/test install .
