branches:
    only:
        - master

language: perl6

perl6:
    - latest

sudo: false

env:
    - PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-nom/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/panda/bin:$PATH

before_install:
    - cd $TRAVIS_BUILD_DIR
    # get t/data
    - git clone https://github.com/atweiden/finn-examples t/data

install:
    - rakudobrew build panda
    - panda --notests installdeps .
