branches:
    only:
        - master

language: perl6

perl6:
    - latest

sudo: false

addons:
  apt:
    sources:
        - deadsnakes
        - ubuntu-toolchain-r-test
    packages:
        - python3.5
        - python3-pip

env:
    - PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-nom/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/panda/bin:~/.local/bin:$PATH

before_install:
    # install buildinspace/peru
    - pip3 install --user peru
    # get finn-examples
    - cd $TRAVIS_BUILD_DIR
    - peru --file=.peru.yml --sync-dir="$PWD" sync

install:
    - rakudobrew build panda
    - panda --notests installdeps .
