branches:
    only:
        - master

language: perl6

perl6:
    - latest

sudo: false

env:
    - PATH=~/.rakudobrew/bin:$PATH

install:
    - cd $TRAVIS_BUILD_DIR
    - rakudobrew build zef
    - zef build .
    - zef --deps-only --/test install .
